name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      portal:
        type: boolean
        description: Portal
      dashboard:
        type: boolean
        description: Dashboard
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
          echo "portal is ${{ github.event.inputs.portal }}" / ${{ inputs.portal }} 
          echo "dashboard is ${{ github.event.inputs.dashboard }}" / ${{ inputs.dashboard }} 
          echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }}
          
