name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        options:
        - QA
        - DEV
        - UAT
      enable feature flag:
        type: boolean
        description: Enable Feature Flag
      testing type:
        type: choice
        description: Testing Type
        options:
        - Smoke
        - Regression
        - Sanity
      textbox:
        type: string
        description: Enter User Name
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.enable feature flag }}" / ${{ inputs.boolean }} 
          echo "choice is ${{ github.event.inputs.testing type }}" / ${{ inputs.choice }}
          echo "string is ${{ github.event.inputs.textbox }}" / ${{ inputs.textbox }}
          
